# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Demo frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: sudo chown -R $USER:$USER /var/www
    - run: npm run build --if-present
    - run: rm -rf /var/www/demo_devops_frontend
    - run: cp -r /home/ubuntu/actions-runner/_work/demo_devops_frontend/demo_devops_frontend/build/*  /var/www/html
    - run: sudo systemctl restart apache2
